name: Download Weather Daily

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run scraper script
      run: python main.py