name: Download Weather Daily

on:
  schedule:
    - cron: "45 11 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Remove ChromeDriver
      run: sudo rm -rf /usr/local/share/chromedriver-linux64

    - name: Remove all Chrome installations
      run: |
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /etc/alternatives/google-chrome
        sudo rm -rf /opt/google/chrome/google-chrome

    ###############################################
    # Install Chrome and ChromeDriver
    - name: Install jq
      run: sudo apt-get -y install jq

    - name: Install latest compatible versions of Chrome and ChromeDriver
      run: |
        JSON_URL="https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json"
        CHROME_VERSION=$(curl -s $JSON_URL | jq -r '.channels.Stable.version')
        CHROME_URL=$(curl -s $JSON_URL | jq -r '.channels.Stable.downloads.chrome[] | select(.platform == "linux64").url')
        CHROMEDRIVER_URL=$(curl -s $JSON_URL | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64").url')
        echo "Chrome Version: $CHROME_VERSION"
        echo "Chrome URL: $CHROME_URL"
        echo "ChromeDriver URL: $CHROMEDRIVER_URL"
        echo "CHROME_URL=$CHROME_URL" >> $GITHUB_ENV
        echo "CHROMEDRIVER_URL=$CHROMEDRIVER_URL" >> $GITHUB_ENV

    - name: Install Chrome
      run: |
        echo "Chrome URL: $CHROME_URL"
        wget -O chrome-linux64.zip "$CHROME_URL"
        unzip chrome-linux64.zip
        sudo mkdir /usr/local/share/chromium
        sudo mv chrome-linux64 /usr/local/share/chromium/chrome-linux
        sudo chmod +x /usr/local/share/chromium/chrome-linux

    - name: Install ChromeDriver
      run: |
        echo "ChromeDriver URL: $CHROMEDRIVER_URL"
        wget "$CHROMEDRIVER_URL" -O chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64 /usr/local/share
        sudo chmod +x /usr/local/share/chromedriver-linux64
    ###############################################

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Selenium Version
      run: pip show selenium

    - name: Run scraper script and upload to DynamoDB
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: python upload_daily_weather.py