name: Download Weather Manually

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Remove Chrome
      run: sudo apt purge google-chrome-stable

    - name: Remove default Chromium
      run: sudo apt purge chromium-browser

    - name: Remove Existing ChromeDriver
      # Purging Chromium does not remove the ChromeDriver
      run: sudo rm -f /usr/bin/chromedriver

    - name: Install a new Chromium
      run: sudo apt install -y chromium-browser

    - name: Check Chromium Version
      run: chromium-browser --version

    - name: Check ChromeDriver Version
      run: chromedriver --version

    - name: Check ChromeDriver Installation Path
      run: which chromedriver

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Selenium Version
      run: pip show selenium

    - name: Run scraper script and upload to DynamoDB
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: python upload_daily_weather.py