name: Download Weather Manually

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: DEBUG - Print PATH
      run: echo $PATH

    - name: DEBUG - 1. List Files and Folders in /usr/bin
      run: ls -l /usr/bin

    - name: DEBUG - List Files and Folders in /usr/local/share
      run: ls -l /usr/local/share

    - name: DEBUG - 1. List Files and Folders in /usr/bin/chromedriver
      run: ls -l /usr/bin/chromedriver

    - name: DEBUG - Check Chrome Version
      run: google-chrome --version

    - name: DEBUG - Check ChromeDriver Version
      run: chromedriver --version

    - name: DEBUG - Check Chrome Installation Path
      run: which google-chrome

    - name: DEBUG - Check ChromeDriver Installation Path
      run: which chromedriver

#    - name: Remove Stable Chrome
#      run: sudo apt purge --auto-remove google-chrome-stable
#
#    - name: Remove Chromium
#      run: sudo rm -rf /usr/local/share/chromium/chrome-linux
#
    - name: Remove ChromeDriver
      run: |
        sudo rm -rf /usr/local/share/chromedriver-linux64/chromedriver
        sudo rm -rf /usr/bin/chromedriver

    - name: DEBUG - 1.5 List Files and Folders in /usr/bin
      run: ls -l /usr/bin

    ###############################################
    # Install Chrome and ChromeDriver
    - name: Install jq
      run: sudo apt-get -y install jq

    - name: Install latest compatible versions of Chrome and ChromeDriver
      run: |
        JSON_URL="https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json"
        CHROME_VERSION=$(curl -s $JSON_URL | jq -r '.channels.Stable.version')
        CHROME_URL=$(curl -s $JSON_URL | jq -r '.channels.Stable.downloads.chrome[] | select(.platform == "linux64").url')
        CHROMEDRIVER_URL=$(curl -s $JSON_URL | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64").url')
        echo "Chrome Version: $CHROME_VERSION"
        echo "Chrome URL: $CHROME_URL"
        echo "ChromeDriver URL: $CHROMEDRIVER_URL"
        echo "CHROME_URL=$CHROME_URL" >> $GITHUB_ENV
        echo "CHROMEDRIVER_URL=$CHROMEDRIVER_URL" >> $GITHUB_ENV

    - name: Install Chrome
      run: |
        echo "Chrome URL: $CHROME_URL"
        wget -O chrome-linux64.zip "$CHROME_URL"
        unzip chrome-linux64.zip
        sudo mv chrome-linux64 /usr/bin/chrome
        sudo chmod +x /usr/bin/chrome

    - name: Install ChromeDriver
      run: |
        echo "ChromeDriver URL: $CHROMEDRIVER_URL"
        wget "$CHROMEDRIVER_URL" -O chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64 /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    ###############################################

    - name: DEBUG - Print PATH
      run: echo $PATH

    - name: DEBUG - 2. List Files and Folders in /usr/bin
      run: ls -l /usr/bin

    - name: DEBUG - 2. List Files and Folders in /usr/bin/chromedriver
      run: ls -l /usr/bin/chromedriver

    - name: DEBUG - 2. List Files and Folders in /usr/bin/chrome
      run: ls -l /usr/bin/chrome

#    - name: Check Chrome Version
#      run: google-chrome --version

#    - name: Check ChromeDriver Version
#      run: chromedriver --version

    - name: Check ChromeDriver Installation Path
      run: which chromedriver

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Selenium Version
      run: pip show selenium

#    - name: Run scraper script and upload to DynamoDB
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      run: python upload_daily_weather.py